uid: uhm:solar_switch
label: Solar Switch
description: This template creates a very simple rule that will allow you to control the state of a device based on the electricity that your house is spending.
configDescriptions:
  - name: SolarSwitch
    type: TEXT
    context: item
    filterCriteria:
      - name: type
        value: Switch
    label: Group of Triggering Items
    description: Group whose members should trigger this rule. At least SolarSwitch should be here.
    required: true
  - name: GridPower
    type: TEXT
    context: item
    label: House Power Meter
    description: Item that will give us the electricity that your house is spending.
    required: true
  - name: TheLoad
    type: TEXT
    context: item
    label: Load to control
    description: The load that this rule will control.
    required: true
  - name: SwitchOnThreshold
    type: TEXT
    context: item
    filterCriteria:
      - name: type
        value: number
    label: Switch On Threshold
    description: Switch that sets the threshold to switch on the load
    required: true
  - name: SwitchOffThreshold
    type: TEXT
    context: item
    filterCriteria:
      - name: type
        value: number
    label: Switch Off Threshold
    description: Switch that sets the threshold to switch off the load
    required: true
  - name: NotificationUser
    type: TEXT
    context: email
    label: Openhab User to send change notifications
    defaultValue: default
    description: Where to send notifications
    required: false

triggers:
  - id: "2"
    configuration:
      itemName: "{{SolarSwitch}}"
    type: core.ItemStateChangeTrigger
conditions: []
actions:
  - inputs: {}
    id: "1"
    configuration:
      type: application/javascript;version=ECMAScript-2021
      script: >-
      
        var notificationsuser = '{{NotificationUser}}';
        
        var logger = log('oh_solar_sw.'+ruleUID);
        
        var solarswitch = items.getItem("{{SolarSwitch}}");

        var laststate;
        
        var onthreshold = items.getItem("{{SwitchOnThreshold}}").state;
        
        var offthreshold = items.getItem("{{SwitchOffThreshold}}").state;
        
        var gridpower = items.getItem("{{GridPower}}").state;
        
        var theload = items.getItem("{{TheLoad}}");

        //laststate posible values: //ON, OFF, SOLARSWITCHOFF

        var LASTSTATE_KEY = ruleUID+'_laststate';


        logger.info('UmbralEncendidoAireDormitorio = '+onthreshold);

        logger.info('UmbralApagadoAireDormitorio = '+offthreshold);

        logger.info('gridpower = '+gridpower);


        if (cache.private.exists(LASTSTATE_KEY)) {
          laststate=cache.private.get(LASTSTATE_KEY);
          logger.info('En el if del cache con ultimoestado = '+laststate);
          }
        else {
          laststate="SOLARSWITCHOFF";
          cache.private.put(LASTSTATE_KEY,laststate);
          logger.info('En el else del cache con ultimoestado = '+laststate);
          }

        if(solarswitch.state=='OFF') {
          if(notificationsuser != 'nouser@mail.account') {actions.NotificationAction.sendNotification(notificationsuser, "Solar switch off")};
          theload.sendCommandIfDifferent('OFF');
          cache.private.put(LASTSTATE_KEY, 'SOLARSWITCHOFF');
        }

        else {
          if(laststate=='SOLARSWITCHOFF') {
            logger.info('Someone just initiated Solar Switch, and the load state is '+theload.state);
            if(notificationsuser != 'nouser@mail.account') {actions.NotificationAction.sendNotification(notificationsuser, "Solar switch on")};
            cache.private.put(LASTSTATE_KEY, theload.state);
            laststate='OFF'
          }
          if(laststate=='ON') {
            if (theload.state=='OFF') {
              if(notificationsuser != 'nouser@mail.account') {actions.NotificationAction.sendNotification(notificationsuser, "Solar Switch: Someone switched off manually the device, deactivating the rule")};
              cache.private.put(LASTSTATE_KEY, 'SOLARSWITCHOFF');
              solarswitch.sendCommand('OFF');
            }
            else {
              if (gridpower>offthreshold) {
                logger.info('Se ha ido al gridpower> con gridpower '+gridpower+ ' y offthreshold '+offthreshold);
                theload.sendCommandIfDifferent('OFF');
                cache.private.put(LASTSTATE_KEY, 'OFF');
                if(notificationsuser != 'nouser@mail.account') {actions.NotificationAction.sendNotification(notificationsuser, "Solar Switch: solar power is lower than the off threshold, switching off the device")};
              }
            }
          }
          if(laststate=='OFF') {
            logger.info('En el if del laststate con loadstate = '+theload.state);
            if (theload.state=='ON') {
              if(notificationsuser != 'nouser@mail.account') {actions.NotificationAction.sendNotification(notificationsuser, "Solar Switch: Someone switched on manually the device, deactivating the rule")};
              cache.private.put(LASTSTATE_KEY, 'SOLARSWITCHOFF');
              solarswitch.sendCommand('OFF');
            }
            else {
              logger.info('En el else del loadstate con gripower = '+gridpower+' onthreshold = '+onthreshold);
              if (gridpower<onthreshold) {
                theload.sendCommandIfDifferent('ON');
                logger.info('En el if del grid< con loadstate = '+theload.state);
                cache.private.put(LASTSTATE_KEY, 'ON');
                if(notificationsuser != 'nouser@mail.account') {actions.NotificationAction.sendNotification(notificationsuser, "Solar Switch: solar power is higher than the on threshold, switching on the device")};
              }
              else logger.info('se ha ido al else');
            }
          }  
        }
    type: script.ScriptAction
