configuration: {}
triggers:
  - id: "2"
    configuration:
      itemName: SolarControl
    type: core.ItemStateChangeTrigger
conditions: []
actions:
  - inputs: {}
    id: "1"
    configuration:
      type: application/javascript;version=ECMAScript-2021
      script: >-
	var notificationsuser = 'nouser@mail.account';
        var logger = log('rules_tools.'+ruleUID);
        var solarswitch = items.getItem("SolarControl");
        var laststate = items.getItem("SolarControllaststate");
        var onthreshold = items.getItem("Onthreshold").state;
        var offthreshold = items.getItem("Offthreshold").state;
        var gridpower = -items.getItem("FroniusSymoInverter_GridPower").state;
        var theload = items.getItem("ACDeviceSalon_Power");

        //laststate posible values:
        //ON, JUSTON, OFF, JUSTOFF, SOLARSWITCHOFF

        if(solarswitch.state=='OFF') {
          if(notificationsuser != 'nouser@mail.account') {actions.NotificationAction.sendNotification(notificationsuser, "Solar switch off")};
          theload.sendCommandIfDifferent('OFF');
          laststate.postUpdate('SOLARSWITCHOFF');
        }

        else {
          if(laststate.state=='SOLARSWITCHOFF') {
            logger.info('Someone just initiated Solar Switch');
            actions.NotificationAction.sendNotification("nouser@mail.account", "Starting SolarSwitch");
            laststate.postUpdate(theload.state);
          }
          if(laststate.state=='ON') {
            if (theload.state=='OFF') {
              if(notificationsuser != 'nouser@mail.account') {actions.NotificationAction.sendNotification(notificationsuser, "Solar Switch: Someone switched off manually the device, deactivating the rule")};
              laststate.postUpdate('SOLARSWITCHOFF');
              solarswitch.sendCommand('OFF');
            }
            else {
              if (gridpower<offthreshold) {
                theload.sendCommandIfDifferent('OFF');
                laststate.postUpdate('JUSTOFF');
                if(notificationsuser != 'nouser@mail.account') {actions.NotificationAction.sendNotification(notificationsuser, "Solar Switch: solar power is lower than the threshold, switching off the device")};
              }
            }
          }
          if(laststate.state=='OFF') {
            if (theload.state=='ON') {
              if(notificationsuser != 'nouser@mail.account') {actions.NotificationAction.sendNotification(notificationsuser, "Solar Switch: Someone switched on manually the device, deactivating the rule")};
              laststate.postUpdate('SOLARSWITCHOFF');
              solarswitch.sendCommand('OFF');
            }
            else {
              if (gridpower>onthreshold) {
                theload.sendCommandIfDifferent('ON');
                laststate.postUpdate('JUSTON');
                if(notificationsuser != 'nouser@mail.account') {actions.NotificationAction.sendNotification(notificationsuser, "Solar Switch: solar power is higher than the threshold, switching on the device")};
              }    
            }
          }  
          if(laststate.state=='JUSTON') {
            //put here the action if juston
            laststate.postUpdate('ON');
          }
          if(laststate.state=='JUSTOFF') {
            //put here the action if justoff
            laststate.postUpdate('OFF');
          }
        }
    type: script.ScriptAction
